name: CI Pipeline for Assignment 1
 
# Temporary trigger on push to feature branch for testing
on:
  push:
    branches:
      - feature-branch  
 
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
 
    - name: Build Docker Image
      run: |
        docker build -t express-app .
 
  run:
    name: Run Docker Container
    runs-on: ubuntu-latest
    needs: build
 
    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
 
    - name: Run the Docker Container
      run: |
        docker run -d --name express-app -p 8080:8080 express-app
 
    - name: Verify Container is Running
      run: |
        docker ps | grep express-app
 
  stop:
    name: Stop Docker Container
    runs-on: ubuntu-latest
    needs: run
 
    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
 
    - name: Stop and Remove Container
      run: |
        docker stop express-app
        docker rm express-app
